import { Inter } from "next/font/google";
import "semantic-ui-css/semantic.min.css";
import "@/scss/global.scss";
import { AuthProvider } from "@/contexts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <body  suppressHydrationWarning={true}>
        <AuthProvider>{children}</AuthProvider> 
        {/* {children} */}
      </body>
    </html>
  );
}
